# Generated by Django 4.2.19 on 2025-03-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Squadra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("sconfitte_consective", models.IntegerField(default=0)),
                ("vittorie_consective", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Squadra",
                "verbose_name_plural": "Squadre",
                "ordering": ["-created_at"],
            },
        ),
    ]
